### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by shahryarshah** [lobaro/lobaro-coap#53]
Hello, I want to use this library on windows and I am facing an error which tells me "sched.h" doesn't exist.
I googled for this and I got that I have to use Linux but based on documentation this lib is introduced as independent from the platform which is processed on. am I missing something here?

**Comment by niondir** [comment]
It's actually developed on embedded devices. I guess it will ne some porting work to run on windows.

**Comment by shahryarshah** [comment]
Hello, I actually encountered this issue:
" liblobaro_coap.h" uses "sched.h" and it doesn't work on windows and based on my searches I had to work with linux friendly environments on windows.
This made me actually switch to linux so everything works fine now.
but thanks for your attention.
