### ISSUE TITLE
Create include directory to help include namespaced header files

### ISSUE THREAD

**Issue by NZSmartie** [Lobaro/lobaro-coap#7]
Before the rebase in 0fa8289f1708ec2f6fc8f5ba032697750f439225, I set my makefile to include the base folder which lobaro-coap was residing in. So my project's includes looked like:

```c
#include "lobaro-coap/coap.h"
```

Namespacing the include files makes it easier when dealing multiple libraries or project file names that conflict. 
In my case, esp-idf has included it's own own ported version of libcoap which I don't want to use. So `#include "coap.h"` could either mean libcoap's coap.h, or lobaro-coap's coap.h which my compiler isn't too happy about.

with the files now sitting under `/src` It would require me to create a symbolic link to fix the issue or maybe branch and rename the folder.

Instead I would like to propose that header files are moved to `/include/lobaro-coap/` under the project root directory to help clean up potentially conflicting names.

**Comment by Niondir** [comment]
What about using the library as a precompiled .a file and just reference the `liblobaro_coap.h` file which now contains most of the required public API?

It's possible after the api_refactoring. Anyway the only file you need now should be "liblobaro_coap.h" - we can move even more definitions there, it contains only the ones I needed yet.

**Comment by Niondir** [comment]
As discussed in chat and my previous comment the issue is solved in a different way now. I don't think it's the end of header file refactoring yet but it's in a usable shape.
