### ISSUE TITLE
Add "Getting started" documentation

### ISSUE THREAD

**Issue by Niondir** [lobaro/lobaro-coap#9]
Goal should be to have a brief tutorial on how compile and use the library. 
Something like: "compile" -> "run tests" -> "take .a file and one .h file to your own project" -> "how to setup a few different endpoints"

The getting started could be in the Wiki or Readme and in future might link to more detailed tutorials that could explain specific setups e.g. for Arduino, the EPS, setup with different IDE's etc. which are out of scope of this issue.

**Comment by nzfarmer1** [comment]
Agree. How do you build and run the tests?

**Comment by Niondir** [comment]
They were created by @davidgraeff but lack documentation. You should take a look into the Travis file.

**Comment by davidgraeff** [comment]
Those tests don't seem to run anymore (I have created them four years ago, according to Github). I would have expected the lobaro contributors to keep the CI green, which apparently hasn't happened.
